### ISSUE TITLE
[Storybook bug] Migrate to the nx 11.6.0

### ISSUE THREAD

**Issue by erkobridee** [erkobridee/nx-nextjs#7]
I tried to update the nx to v11.6 but while I was running the migration 

`nx migrate --run-migrations`

I got an error on the storybook step

<details>
<summary>terminal output</summary>
<pre><code>>  NX  Running migrations from 'migrations.json'

Running migration add-js-include-11.6.0
Successfully finished add-js-include-11.6.0
---------------------------------------------------------
Running migration update-11-5-3
    app: no storybook configured. skipping migration...
    app-e2e: no storybook configured. skipping migration...
    nextjs: no storybook configured. skipping migration...
    nextjs-e2e: no storybook configured. skipping migration...
    shared-components-e2e: no storybook configured. skipping migration...
Cannot read property 'storybook' of undefined
/${path on my machine}/nx-nextjs/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: /var/folders/sp/xhc5vgjs2v79b14fsrhss4zw0000gq/T/tmp-82734mxX2kYdzjRwV/node_modules/.bin/tao migrate --run-migrations
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at Object.handler (/${path on my machine}/nx-nextjs/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:80:25)
    at Object.runCommand (/${path on my machine}/nx-nextjs/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/${path on my machine}/nx-nextjs/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/${path on my machine}/nx-nextjs/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (/${path on my machine}/nx-nextjs/node_modules/@nrwl/cli/lib/init-local.js:23:13)
    at Object.<anonymous> (/${path on my machine}/nx-nextjs/node_modules/@nrwl/cli/bin/nx.js:42:18)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 82741,
  stdout: null,
  stderr: null
}</code></pre>
</details>

for now, is wait for another newer version to be able to move forward

**Comment by erkobridee** [comment]
solved migrating to nx v12.0.0
